### ISSUE TITLE
GPL License

### ISSUE THREAD

**Issue by quicquid** [sirinath/JVMTrader#1]
Is there any possibility to license the code under a permissive license like GPL 2 or 3?

**Comment by sirinath** [comment]
This is unde ASL 2.0

**Comment by quicquid** [comment]
ASL 2.0 is incompatible with GPL:

`We avoid GPLv3 software because merely linking to it is considered by the GPLv3 authors to create a derivative work. We want to honor their license. Unless GPLv3 licensors relax this interpretation of their own license regarding linking, our licensing philosophies are fundamentally incompatible. This is an identical issue for both GPLv2 and GPLv3.`

**Comment by sirinath** [comment]
ASL 2.0 means you can use in GPL not the other way around: http://www.apache.org/licenses/GPL-compatibility.html
